import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/components/provider";
import ScreenIndicator from "@/components/utils/ScreenIndicator";
import AuthGuard from "@/components/AuthGuard";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${plusJakarta.variable}`}>
      <body
        className={`${plusJakarta.variable} h-screen w-screen flex font-sans overflow-hidden relative`}
      >
        <ReactQueryProvider>
          {" "}
          <Toaster position="top-right" richColors theme="dark" />
          <ScreenIndicator />
          <AuthGuard>{children}</AuthGuard>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
